Enhanced S3 APIs for ECS extension features
EMCECS/ecs-object-client-go pull request #1
Opened 2017-05-12 18:52 UTC by yangb8

2017-06-02 14:14 UTC, DavidASeibert commented on api.go
> +// Package ecs provides a client for ECS Extension.
You should have copyrights in all files.

2017-06-02 14:19 UTC, yangb8 commented on api.go
> +// Package ecs provides a client for ECS Extension.
accepted

2017-06-02 14:28 UTC, DavidASeibert requested changes
One high level pass done, this file only

2017-06-02 14:28 UTC, DavidASeibert commented on api.go
> +func (c *S3) CreateBucketExtRequest(input *CreateBucketInput) (req *request.Request, output *s3.CreateBucketOutput) {
Probably should spell out all of Ext - Extension? Exterior? Extrusion? ;-)

This should apply everywhere you use Ext.

Or, you could use Ecs/ECS to make it even clearer that this is the ECS-specific version. That's probably even better.

2017-06-02 14:28 UTC, DavidASeibert commented on api.go
> +const opGetSystemMetdataSearchKeys = "GetSystemMetdataSearchKeys"
There are a number of metadata misspellings as "Metdata". Please correct those.

2017-06-02 14:28 UTC, DavidASeibert commented on api.go
> +func (c *S3) HeadBucketExtg(input *s3.HeadBucketInput) (*HeadBucketOutput, error) {
Why "Extg"? Should that be "Ext"? It's not clear to me what this means, so use a better name if it's not.

2017-06-02 14:28 UTC, DavidASeibert commented on api.go
> +type CreateBucketInput struct {
I'd move this closer to where it's used in the CreateBucket methods.

2017-06-02 14:28 UTC, DavidASeibert commented on api.go
> +type EmcEcsExtIndexableKey struct {
Is the Emc necessary? If so, we should use EmcEcs everywhere we have our own variant, for consistency. If not, we should use Ecs for all.

2017-06-02 14:28 UTC, DavidASeibert commented on api.go
> +func (s *EmcEcsExtIndexableKey) SetName(v string) *EmcEcsExtIndexableKey {
I'd drop the Ext after EmcEcs (or just Ecs) everywhere, it's redundant (or should be).

2017-06-02 14:40 UTC, yangb8 commented on api.go
> +func (c *S3) CreateBucketExtRequest(input *CreateBucketInput) (req *request.Request, output *s3.CreateBucketOutput) {
accepted. will change it to "Extension". unnecessary to add ecs keyword because the github URL includes emcecs.

2017-06-02 14:41 UTC, yangb8 commented on api.go
> +const opGetSystemMetdataSearchKeys = "GetSystemMetdataSearchKeys"
accepted.

2017-06-02 14:43 UTC, yangb8 commented on api.go
> +func (c *S3) HeadBucketExtg(input *s3.HeadBucketInput) (*HeadBucketOutput, error) {
accepted. will delete it. this function "HeadBucketExtg" is junk. "HeadBucketExt" is valid one and in this file as well.

2017-06-02 14:44 UTC, yangb8 commented on api.go
> +type CreateBucketInput struct {
accepted

2017-06-02 14:44 UTC, yangb8 commented on api.go
> +type EmcEcsExtIndexableKey struct {
accepted

2017-06-02 14:44 UTC, yangb8 commented on api.go
> +func (s *EmcEcsExtIndexableKey) SetName(v string) *EmcEcsExtIndexableKey {
accepted

2017-06-02 17:13 UTC, yangb8 commented on api.go
> +type CreateBucketInput struct {
I looked into further, actually,  xxxInput and xxxOutput structures are located after xxxRequest functions. I'd prefer to keep it where it is. (the location sequence in api.go is all request functions --> input/output structures --> misc util functions)

2017-06-05 22:40 UTC, yangb8 commented
@DavidASeibert any further comments?

2017-06-08 19:36 UTC, DavidASeibert approved these changes
There are still a bunch of places where "Md" is used, apparently for "Metadata". Please change those to use the full word, so developers don't need to even think about what the abbreviation might be. It's approved after that.

2017-06-08 19:36 UTC, DavidASeibert commented on api.go
> +	QueryMds        []*EcsQueryMds `locationName:"queryMds" type:"list" flattened:"true"`
"Mds" should be Metadata, it's spelled out in full everywhere else.

2017-06-08 19:36 UTC, DavidASeibert commented on api.go
> +type EcsQueryMds struct {
As above - "Mds" and "Md" should be Metadata, that's spelled out in full everywhere else. There are more instances below, please find and fix them all. Once that's done, it's approved.

2017-06-08 19:48 UTC, yangb8 commented on api.go
> +type EcsQueryMds struct {
`QueryMds` is the field name in response body of metadata search, that’s why I used that name. So I’ll leave it as it is if you are ok with that.

2017-06-08 19:48 UTC, yangb8 commented on api.go
> +	QueryMds        []*EcsQueryMds `locationName:"queryMds" type:"list" flattened:"true"`
`QueryMds` is the field name in response body of metadata search, that’s why I used that name. So I’ll leave it as it is if you are ok with that.

2017-06-08 20:05 UTC, yangb8 commented on api.go
> +type EcsQueryMds struct {
after discussion with David on slack. the change will be "EcsQueryMds -> QueryMetadata (or EcsQueryMetada) and MdType -> MetadataType (or EcsMetadataType), and leave the other two."

2017-06-08 20:55 UTC, merged